FROM xebialabs/xl-deploy:9.0.5-centos
USER root
RUN yum -y install rpm
COPY conf /opt/xebialabs/xl-deploy-server/conf
COPY conf/logback.xml /opt/xebialabs/xl-deploy-server/conf
COPY conf/deployit-license.lic /opt/xebialabs/xl-deploy-server/conf
COPY conf/deployit.conf /opt/xebialabs/xl-deploy-server/conf
COPY id_rsa /opt/xebialabs/xl-deploy-server
COPY id_rsa.pub /opt/xebialabs/xl-deploy-server

RUN mkdir -p /opt/xebialabs/xl-deploy-server/ext/zkb/poc/scripts
COPY ext/synthetic.xml /opt/xebialabs/xl-deploy-server/ext/synthetic.xml
COPY ext/xl-rules.xml /opt/xebialabs/xl-deploy-server/ext/xl-rules.xml
COPY ext/zkb/* /opt/xebialabs/xl-deploy-server/ext/zkb/
COPY ext/scripts/* /opt/xebialabs/xl-deploy-server/ext/scripts/
# COPY samples/rules-demo-plugin-9.0.5.xldp /opt/xebialabs/xl-deploy-server/plugins
# COPY samples/task-monitor-plugin-9.0.5.xldp /opt/xebialabs/xl-deploy-server/plugins
# COPY samples/ui-extension-demo-plugin-9.0.5.xldp /opt/xebialabs/xl-deploy-server/plugins

RUN find /opt/xebialabs/xl-deploy-server/ext
RUN find /opt/xebialabs/xl-deploy-server/conf
RUN find /opt/xebialabs/xl-deploy-server -maxdepth 1

ENTRYPOINT ["/opt/xebialabs/tini","--","/opt/xebialabs/xl-deploy-server/bin/run-in-container.sh"]
